name: Deploy to EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java and Maven
      uses: actions/setup-java@v3
      with:
        java-version: '17' # Cambia según la versión de Java que uses
        distribution: 'temurin'

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        aws --version

    - name: Deploy to EC2
      run: |
        # Configurar AWS CLI
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-2 # Cambia la región según tu configuración de AWS

        # Conectar a EC2 y reiniciar la aplicación
        ssh -o StrictHostKeyChecking=no ubuntu@3.17.75.72 << 'EOF'
          cd /home/ubuntu/EC2_prueba/aws
          git pull origin main
          mvn clean install
          sudo systemctl restart EC2_prueba.service # Si tu aplicación está configurada como un servicio
        EOF

